apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhtap-test-project
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-test-project
    app.kubernetes.io/part-of: rhtap-test-project
  name: rhtap-test-project
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rhtap-test-project
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rhtap-test-project
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mcostant-tenant/rhtap-test-project/rhtap-test-project@sha256:5bc7d9cf5b0385d526e0466558fc27bc5d0353d37583d834bece264a0a4923a5
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
