apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhtap-test-project
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-test-project
    app.kubernetes.io/part-of: rhtap-test-project
  name: rhtap-test-projectqi43
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: rhtap-test-project
    weight: 100
status: {}
